-- Generated by Stylix
local wezterm = require("wezterm")

local config = wezterm.config_builder()

config.color_scheme = "GruvboxDarkHard"


config.font = wezterm.font_with_fallback({
	"JetBrainsMono Nerd Font",
	"Noto Color Emoji",
})

config.font_size = 11.5
config.command_palette_font_size = 13

config.colors = {
	tab_bar = {
		active_tab = {
			bg_color = "#1b1b1b",
			fg_color = "#d5c4a1",
		},
		inactive_tab_hover = {
			bg_color = "#d5c4a1",
			fg_color = "#1b1b1b",
		},
		new_tab_hover = {
			bg_color = "#d5c4a1",
			fg_color = "#1b1b1b",
		},
	},
}

return config
