{
 "title": "AdGuard Home Exporter",
 "description": "This is a AdGuard Home dashboard when using the https://github.com/henrywhitaker3/adguard-exporter Prometheus exporter",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(adguard_running,server)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_running{server=\"$server\"}",
     "legendFormat": "{{ legend }}"
    }
   ]
  },
  {
   "title": "DHCP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_dhcp_enabled{server=\"$server\"}",
     "legendFormat": "{{ legend }}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_running{server=\"$server\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "% Blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(adguard_queries_blocked{server=\"$server\"}/ adguard_queries{server=\"$server\"}) * 100"
    }
   ]
  },
  {
   "title": "Processing Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(adguard_processing_time_milliseconds_sum{server=\"$server\"}[$__rate_interval])) / sum(rate(adguard_processing_time_milliseconds_count{server=\"$server\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Top Queries by Domain",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, increase(adguard_top_queried_domains{server=\"$server\"}[$__range]))",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Top Clients",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, increase(adguard_top_clients{server=\"$server\"}[$__range]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DNS queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(adguard_queries[$__rate_interval])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Query Types",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(adguard_query_types{server=\"$server\"}[$__range])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (upstream) (rate(adguard_processing_time_milliseconds_sum[5m])) / sum by (upstream) (rate(adguard_processing_time_milliseconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries Blocked/Replaced",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(adguard_queries_blocked[$__rate_interval])",
     "legendFormat": "Blocked {{server}}"
    },
    {
     "expr": "rate(adguard_replaced_safesearch[$__rate_interval])",
     "legendFormat": "Replaced SafeSearch {{server}}"
    },
    {
     "expr": "rate(adguard_replaced_safebrowsing[1m])",
     "legendFormat": "Replaced SafeBrowsing"
    },
    {
     "expr": "sum(adguard_replaced_parental{server=\"$server\"})",
     "legendFormat": "Replaced Parental {{server}}"
    }
   ]
  },
  {
   "title": "Client Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(adguard_top_clients[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(15, sum by (client, name) (increase(adguard_top_clients{server=\"$server\"}[$__range])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (client, name) (rate(adguard_processing_time_milliseconds_sum[$__rate_interval]))  / sum by (client, name) (rate(adguard_processing_time_milliseconds_count[$__rate_interval]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Blocked Domains",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(15, sum by (domain) (increase(adguard_top_blocked_domains[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Queries",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "topk(15, sum by (domain) (increase(adguard_top_queried_domains[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DHCP Leases",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "adguard_dhcp_leases{server=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstreams",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 30 },
   "targets": [
    {
     "expr": "topk(15, sum by (upstream) (increase(adguard_top_upstreams{server=\"$server\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}