theme = "gruvbox_dark_hard"

[editor]
true-color = true
color-modes = true
bufferline = "multiple"
line-number = "relative"
scrolloff = 8
auto-pairs = false

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "▏"
render = true
skip-levels = 1

[editor.file-picker]
git-ignore = false
hidden = false

[editor.lsp]
display-messages = true

[editor.statusline]
left = [ 
  "mode",
  "spinner",
  "spacer",
  "version-control",
  "spacer",
  "file-name",
  "file-modification-indicator"
]
center = []
right = [
  "diagnostics", 
  "spacer",
  "selections", 
  "spacer",
  "position-percentage",
  "position"
]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-d = ["half_page_down", "goto_window_center"]
C-u = ["half_page_up",   "goto_window_center"]
