theme = "base16"

[editor]
true-color = true
color-modes = true
bufferline = "multiple"
line-number = "relative"
scrolloff = 8

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "▏"
render = true

[editor.file-picker]
git-ignore = false
hidden = false

[editor.lsp]
display-messages = true

[editor.statusline]
left = [ 
  "mode",
  "spinner",
  "spacer",
  "version-control",
  "spacer",
  "file-name",
  "file-modification-indicator"
]
center = []
right = [
  "diagnostics", 
  "spacer",
  "selections", 
  "spacer",
  "position-percentage",
  "position"
]


[keys.normal."h"]
h = "match_brackets"
s = "surround_add"
r = "surround_replace"
d = "surround_delete"
a = "select_textobject_around"
i = "select_textobject_inner"

[keys.normal."g"]
m = "goto_line_start"
i = "goto_line_end"
l = "goto_implementation"
h = "goto_last_modified_file"

[keys.normal]
# Colemak remaps
m = "move_char_left"
n = "move_visual_line_down"
N = "keep_selections"
e = "move_visual_line_up"
i = "move_char_right"
j = "move_next_word_end"
k = "search_next"
K = "search_prev"
l = "insert_mode"

esc = ["collapse_selection", "keep_primary_selection"]
X   = "extend_line_above"
A-r = ":reflow"
C-d = ["half_page_down", "goto_window_center"]
C-u = ["half_page_up",   "goto_window_center"]

A-j = [
  "extend_to_line_bounds",
  "delete_selection",
  "paste_after",
]
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]

[keys.normal."space"]
C = ":config-open" # Open helix config
L = ":open ~/.config/helix/languages.toml" # Open languages.toml

[keys.select]
m = "extend_char_left"
n = "extend_line_down"
N = "keep_selections"
e = "extend_line_up"
i = "extend_char_right"
j = "move_next_word_end"
k = "extend_search_next"
K = "extend_search_prev"
l = "insert_mode"

[keys.select."h"]
h = "match_brackets"
s = "surround_add"
r = "surround_replace"
d = "surround_delete"
a = "select_textobject_around"
i = "select_textobject_inner"

A-j = [
  "extend_to_line_bounds",
  "delete_selection",
  "paste_after",
]
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
