theme = "catppuccin_mocha"

[editor]
true-color = true
color-modes = true
bufferline = "always"
line-number = "relative"
scrolloff = 8

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "▏"
render = true

[editor.lsp]
display-messages = true

[editor.statusline]
left = [ 
  "mode",
  "spinner",
  "spacer",
  "version-control",
  "spacer",
  "file-name",
  "file-modification-indicator"
]
center = []
right = [
  "diagnostics", 
  "spacer",
  "selections", 
  "spacer",
  "position-percentage",
  "position"
]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X   = "extend_line_above"
A-r = ":reflow"
# C-d = ["half_page_down", "align_view_center"]
# C-u = ["half_page_up",   "align_view_center"]
A-f = [
  ":new", 
  ":insert-output lf-pick", 
  "select_all", 
  "split_selection_on_newline", 
  "goto_file", 
  "goto_last_modified_file", 
  ":bc!",
]

A-j = [
  "extend_to_line_bounds",
  "delete_selection",
  "paste_after",
]
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]

[keys.normal."space"]
C = ":config-open" # Open helix config
L = ":open ~/.config/helix/languages.toml" # Open languages.toml

[keys.select]
A-j = [
  "extend_to_line_bounds",
  "delete_selection",
  "paste_after",
]
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]