theme = "base16_transparent"

[editor]
true-color = true
color-modes = true
bufferline = "multiple"
line-number = "relative"
scrolloff = 8

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "▏"
render = true

[editor.file-picker]
git-ignore = false
hidden = false

[editor.lsp]
display-messages = true

[editor.statusline]
left = [ 
  "mode",
  "spinner",
  "spacer",
  "version-control",
  "spacer",
  "file-name",
  "file-modification-indicator"
]
center = []
right = [
  "diagnostics", 
  "spacer",
  "selections", 
  "spacer",
  "position-percentage",
  "position"
]

[keys.normal."h"]
h = "match_brackets"
s = "surround_add"
r = "surround_replace"
d = "surround_delete"
a = "select_textobject_around"
i = "select_textobject_inner"

[keys.normal]
m = "move_char_left"
n = "move_visual_line_down"
e = "move_visual_line_up"
i = "move_char_right"
j = "move_next_word_end"
k = "search_next"
l = "insert_mode"



esc = ["collapse_selection", "keep_primary_selection"]
X   = "extend_line_above"
A-r = ":reflow"
C-d = ["half_page_down", "goto_window_center"]
C-u = ["half_page_up",   "goto_window_center"]
# A-f = [
#   ":new", 
#   ":insert-output lf-pick", 
#   "select_all", 
#   "split_selection_on_newline", 
#   "goto_file", 
#   "goto_last_modified_file", 
#   ":bc!",
# ]

A-j = [
  "extend_to_line_bounds",
  "delete_selection",
  "paste_after",
]
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]

[keys.normal."space"]
C = ":config-open" # Open helix config
L = ":open ~/.config/helix/languages.toml" # Open languages.toml

[keys.select]
A-j = [
  "extend_to_line_bounds",
  "delete_selection",
  "paste_after",
]
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
