theme = "monokai_pro_spectrum"

[editor]
true-color = true
bufferline = "always"
color-modes = true
line-number = "relative"
scrolloff = 8

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "▏"
render = true

[editor.lsp]
display-messages = true

[editor.statusline]
left = [ 
  "mode",
  "spinner",
  "spacer",
  "version-control",
  "spacer",
  "file-name",
  "file-modification-indicator"
  ]
center = []
right = [
  "diagnostics", 
  "selections", 
  "position-percentage",
  "position"
  ]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = "extend_line_above"
A-r = ":reflow"
# C-u = ["half_page_up",   "align_view_center"]
C-d = ["half_page_down", "align_view_center"]
