[[language]]
auto-format = true
name = "rust"

[language.config.checkOnSave]
command = "clippy"

[[language]]
name = "latex"

[language.soft-wrap]
enable = true
wrap-at-text-width = true

[language.config.texlab]
[language.config.texlab.build]
forwardSearchAfter = true
onSave = true

executable = "tectonic"
args = [
  "-X",
  "compile",
  "%f", 
  "--synctex",
  "--keep-logs",
  "--keep-intermediates"
  ]

[language.config.texlab.chktex]
onEdit = true

[language.config.texlab.forwardSearch]
executable = "zathura"
# args = [ "--synctex-forward", "%l:%c:%f", "%p" ]

