[[language]]
auto-format = true
name = "rust"

[language-server.rust-analyzer.checkOnSave]
command = "clippy"

[[language]]
name = "latex"
language-servers = ["texlab", "ltex" ]

[language.soft-wrap]
enable = true
wrap-at-text-width = true


[language-server.texlab.config.texlab.build]
forwardSearchAfter = true
onSave = true

executable = "tectonic"
args = [
  "-X",
  "compile",
  "%f", 
  "--synctex",
  "--keep-logs",
  "--keep-intermediates"
  ]

[language-server.texlab.config.texlab.chktex]
onEdit = true

[language-server.texlab.config.texlab.forwardSearch]
executable = "zathura"
# args = [ "--synctex-forward", "%l:%c:%f", "%p" ]

[language-server.ltex]
command = "ltex-ls"
config = { ltex = {language = "da-DK" }}
