return {
    cmd = { 'harper-ls', '--stdio' },
    filetypes = {
        'c',
        'cpp',
        'cs',
        'gitcommit',
        'go',
        'html',
        'java',
        'javascript',
        'lua',
        'markdown',
        'nix',
        'python',
        'ruby',
        'rust',
        'swift',
        'toml',
        'typescript',
        'typescriptreact',
        'haskell',
        'cmake',
        'typst',
        'php',
        'dart',
    },
    settings = {
        ['harper-ls'] = {
            userDictPath = vim.fn.stdpath('config') .. '/spell/en.utf-8.add',
            markdown = { ignore_link_title = true },
        },
    },
}
